language: emacs-lisp
env:
  matrix:
    - EMACS=emacs24
    - EMACS=emacs-snapshot
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y $EMACS
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH="$HOME/.cask/bin:$PATH"
  - export ECUKES_EMACS="$EMACS"
  - cask
script:
  make
